/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'approvePayment' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'claimPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getPaymentStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'submitUserDetails' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'approvePayment' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'claimPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getPaymentStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'submitUserDetails' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };